window.authoritativeCatalogueItems = [
    {
        "sectionId":  "career-development",
        "cataloguePath":  "Career Development",
        "title":  "How to develop professionally",
        "text":  "Considering your next career step? With this 4-module online series you can explore your potential, reflect on your journey, and gain guidance and practical tools to move forward.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=0\u0026sidebarExpanded=true\u0026q=%7B!q.op%3DAND%7D%20%7B!q.op%3DAND%7D%20How%20to%20Develop%20Professionally\u0026rows=4\u0026fq=%7B!tag%3DclassificationIds_41370794%7D%20classificationIds_41370794:(1%2F41370794%2F41374272%2F)",
        "image":  "img/EU_learn_How_to_develop_prof_650x365_107454336.png",
        "format":  "Online",
        "location":  "-",
        "duration":  "3h",
        "info":  "Online • 3h",
        "size":  "wide"
    },
    {
        "sectionId":  "career-development",
        "cataloguePath":  "Career Development",
        "title":  "How to prepare for an internal interview",
        "text":  "This is a hands-on course based on real-life case studies to better prepare for any interview in the EP.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/108489565/description",
        "image":  "img/EU_Learn_How_to_prepare_for_internal_interview_108299500.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "8h",
        "info":  "online/classroom • Brussels/Luxembourg • 8h",
        "size":  "standard"
    },
    {
        "sectionId":  "career-development",
        "cataloguePath":  "Career Development",
        "title":  "Developing your personal brand",
        "text":  "Stand out with confidence. Define your strengths, refine your professional story through a personal bio, and practise presenting yourself in real-life scenarios.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290075/coursetemplates/110236842/description",
        "image":  "img/EU_learn_Develop_personal_brand_650x365_110232425.png",
        "format":  "Classroom ",
        "location":  "Brussels",
        "duration":  "7.5",
        "info":  "Classroom  • Brussels • 7.5",
        "size":  "standard"
    },
    {
        "sectionId":  "career-development",
        "cataloguePath":  "Career Development",
        "title":  "Kick-start your competition preparation",
        "text":  "Are you preparing for a competition? Success isn’t just about studying, but also managing stress, staying sharp, finding information fast, and communicating clearly. Get top tips on how to get there!",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290075/coursetemplates/106732671/description",
        "image":  "img/Kick_start_competition_prep_Image_81343338_98509988.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7H",
        "info":  "Classroom  • Brussels/Luxembourg • 7H",
        "size":  "standard"
    },
    {
        "sectionId":  "career-development",
        "cataloguePath":  "Career Development",
        "title":  "Collection per EP competence",
        "text":  "Thematically curated bundles of short, on-demand courses that help you build one competence at a time.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=78316164",
        "image":  "img/Competences.png",
        "format":  "Online/classroom",
        "location":  "-",
        "duration":  "Variable",
        "info":  "Online/classroom • Variable",
        "size":  "wide"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Public speaking ",
        "text":  "Learn how to structure your speeches and interventions, engage your audience with confidence, and manage speaking stress in this hands-on workshop.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/106321378/description",
        "image":  "img/public_speaker_98919503.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "3,5h",
        "info":  "online/classroom • Brussels/Luxembourg • 3,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Presenting with impact",
        "text":  "Are you speaking at your audience—or truly connecting with them?",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/106481527/description",
        "image":  "img/My_presentation_skills_in_virtual_settings_640x365_51342528_78702904_94765412.jpg",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "online/classroom • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Voice techniques for clear communication",
        "text":  "Make your voice work for you. Learn how to refine your pitch, control your breathing, find the ideal pace, use pauses effectively, and align your body language for impact.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/106322483/description",
        "image":  "img/public_speaking_reading_a_speech_98839391.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "online/classroom • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Tough talks - Mastering the Art of Difficult Conversations",
        "text":  "Difficult conversations are hard - but necessary. Learn key skills, practice through role-plays, and prepare to handle them with confidence and clarity.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/106321632/description",
        "image":  "img/EU_learn_Tough_talks_650x365_98569406.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "4h",
        "info":  "online/classroom • Brussels/Luxembourg • 4h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Brand Guidelines for the European Parliament\u0027s Administration",
        "text":  "Do you create documents for an internal or external audience?",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/93851499/description",
        "image":  "img/brand_guidelines_93851484.png",
        "format":  "Online",
        "location":  "-",
        "duration":  "Variable",
        "info":  "Online • Variable",
        "size":  "wide"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "How to facilitate online",
        "text":  "No more boring online meetings without results. Learn how to design interactive, purpose-driven online workshops. Discover how to use Slido, Whiteboard, and Howspace to meet your goals.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/95998135/description",
        "image":  "img/Online_workshop_facilitation_tools__flow__and_best_practices_95959586.png",
        "format":  "Online",
        "location":  "-",
        "duration":  "2h",
        "info":  "Online • 2h",
        "size":  "wide"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Effective networking",
        "text":  "This interactive course will teach you how to build and nurture professional relationships online and in-person to extend your network within the organisation and beyond.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/107223032/description",
        "image":  "img/course_template_description_image_default.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3,5h",
        "info":  "Classroom  • Brussels/Luxembourg • 3,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Clear language essentials",
        "text":  "Learn the principles of clear language and how to apply Parliament’s Citizens’ language guidelines to emails, briefings, and administrative documents to communicate more efficiently.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/104685091/description",
        "image":  "img/Clear_Language_Essentials___Graphic_100496148.png",
        "format":  "Online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "2,5H",
        "info":  "Online/classroom • Brussels/Luxembourg • 2,5H",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Getting the most out of feedback",
        "text":  "Turn feedback into a growth tool. Understand brain reactions, remove barriers, and develop patterns that strengthen trust and performance.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/106317255/description",
        "image":  "img/Getting_the_most_out_of_feedback_93656167.png",
        "format":  "Online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Online/classroom • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Back to school and university",
        "text":  "Designed for EP staff taking part in the Back to School or Back to University Programme, this course helps you contribute with confidence.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/106634610/description",
        "image":  "img/B2S_Training_logo_99210747.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3,5h",
        "info":  "Classroom  • Brussels/Luxembourg • 3,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Visual thinking: Connect challenges to dynamic sketches",
        "text":  "Unleash your creativity! Learn to think, collaborate, and communicate visually through sketch notes that turn complex ideas into clear visuals.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/112115541/coursesessions",
        "image":  "img/PowerVisuals_thumb_650x3652_89137204.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7hrs",
        "info":  "Classroom  • Brussels/Luxembourg • 7hrs",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Navigate your emotional intelligence",
        "text":  "EQ is today one of the most demanded skills at the workspace.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/100536427/coursetemplates/106774919/description",
        "image":  "img/Emotional_intel_650x365_83105060.png",
        "format":  "classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Brainstorming techniques - how to come up with new ideas",
        "text":  "Stuck with the same ideas and inefficient processes? Join this half-day workshop to learn how to brainstorm, unlock creative thinking, generate innovative solutions, and structure your thoughts.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/109611791/description",
        "image":  "img/EU_learn_brainstorming_techniques_650x365_107223191.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3,5h",
        "info":  "Classroom  • Brussels/Luxembourg • 3,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Entry-Level Participatory Leadership",
        "text":  "Learn easy-to-apply techniques to facilitate discussions and invite participation from everyone in your team. Build on your collective intelligence to take better decisions and achieve results.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290075/coursetemplates/106712243/description",
        "image":  "img/EU_learn_Participatory_Leadership_650x3652_82118316.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "24h",
        "info":  "Classroom  • Brussels/Luxembourg • 24h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Train the Trainer",
        "text":  "Whether you’re an occasional or seasoned trainer, strengthen your skills in learning design, workshop facilitation, online delivery, interaction techniques, and effective presentations.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/106321897/description",
        "image":  "img/Train_the_Trainer_postits_94737584.jpg",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "4h",
        "info":  "online/classroom • Brussels/Luxembourg • 4h",
        "size":  "standard"
    },
    {
        "sectionId":  "digital-competences",
        "cataloguePath":  "Digital competencies \u003e IT security \u0026 management \u003e Cybersecurity",
        "title":  "Cybersecurity ",
        "text":  "As systems grow more connected, risks grow faster. Learn how to lead, manage, and defend against modern cyber threats with HBR’s expert insights.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=34286508",
        "image":  "img/EU learn cybersecurity 650x365.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "Variable",
        "info":  "online/classroom • Brussels/Luxembourg • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "digital-competences",
        "cataloguePath":  "Digital competencies \u003e Other applications",
        "title":  "Data Analytics",
        "text":  "Discover how to collect, analyse, and visualise data to uncover insights that drive smarter decisions.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=34288649",
        "image":  "img/course_template_description_image_default.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "online/classroom • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "digital-competences",
        "cataloguePath":  "Digital competencies \u003e Accessibility",
        "title":  "Acessibility",
        "text":  "Learn the principles of accessibility and how to create content and documents that are accessible for all.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/71037089/programmes/111113376/description",
        "image":  "img/EU_learn_Digigtal_Accessibility_learning_path_650x365_111111558.png",
        "format":  "eLearning",
        "location":  "-",
        "duration":  "Variable",
        "info":  "eLearning • Variable",
        "size":  "wide"
    },
    {
        "sectionId":  "digital-competences",
        "cataloguePath":  "Digital competencies \u003e Cloud",
        "title":  "Cloud",
        "text":  "Learn cloud computing skills through training in Azure, AWS services, data management, and cloud architecture.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=115172\u0026fq%2B=subTreeIds:%221%2F0%2F115172%2F%22\u0026fq=%7B!tag%3DsubTreeIds%7D%20subTreeIds:(2%2F0%2F115172%2F34288577%2F)\u0026fq=%7B!tag%3DsubTreeIdsDirect%7D%20subTreeIdsDirect:(3%2F0%2F115172%2F34286060%2F36000577%2F)\u0026sidebarExpanded=true\u0026q=%7B!q.op%3DAND%7D%20*:*\u0026rows=3",
        "image":  "img/EU learn Could apps 650x365.png",
        "format":  "online",
        "location":  "-",
        "duration":  "Variable",
        "info":  "online • Variable",
        "size":  "wide"
    },
    {
        "sectionId":  "digital-competences",
        "cataloguePath":  "Digital competencies \u003e Adobe",
        "title":  "Adobe Acrobat Pro",
        "text":  "Enhance your skills with Adobe Acrobat Pro hands-on training and learn to create, edit, and secure PDFs efficiently.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/35771560/coursetemplates/106312511/description",
        "image":  "img/IT_Adobe_Acrobat_thumbnail_650x365_61423696.jpg",
        "format":  "online",
        "location":  "-",
        "duration":  "7h",
        "info":  "online • 7h",
        "size":  "wide"
    },
    {
        "sectionId":  "digital-competences",
        "cataloguePath":  "Digital competencies \u003e Adobe",
        "title":  "Adobe Premiere Pro CC (step 1)",
        "text":  "Bring your designs to life with this three-day course and learn to edit, enhance, and publish your own videos.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/35771560/coursetemplates/98757260/description",
        "image":  "img/EU_learn_AdobePremiere_650x365_98757256.png",
        "format":  "online",
        "location":  "-",
        "duration":  "21h",
        "info":  "online • 21h",
        "size":  "wide"
    },
    {
        "sectionId":  "digital-competences",
        "cataloguePath":  "Digital competencies ",
        "title":  "Office 365",
        "text":  "Refresh your knowledge and master new functionalities in the Office 365 tools like Word, Excel, and Teams.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=34288636",
        "image":  "img/EU learn Office 365 650x365.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "Variable",
        "info":  "online/classroom • Brussels/Luxembourg • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "digital-competences",
        "cataloguePath":  "Digital competencies \u003e EP/EU applications",
        "title":  "Digital Basics for Newcomers at the EP",
        "text":  "Discover the must-have digital tools behind our daily work. Ideal for newcomers, but helpful for everyone!",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288659/coursetemplates/106312215/description",
        "image":  "img/digital_basics_96084258.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3h",
        "info":  "Classroom  • Brussels/Luxembourg • 3h",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Administrative Skills and Tools",
        "title":  "Staff Regulation training",
        "text":  "Discover the essentials of the Staff Regulations - from recruitment and career development to working time, leave, and pensions.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/100658061/coursetemplates/109778704/description",
        "image":  "img/EU_learn_Staff_Regulations_650x365_02.04.2025_107750574.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "6,5h",
        "info":  "Classroom  • Brussels/Luxembourg • 6,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Administrative Skills and Tools",
        "title":  "Document management",
        "text":  "Discover the essentials of document management, from handling paper and digital records to archiving them properly and preserving the EP\u0027s knowledge and memory.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=0\u0026sidebarExpanded=true\u0026q=%7B!q.op%3DAND%7D%20document%20management\u0026rows=10\u0026fq=%7B!tag%3DsubTreeIdsDirect%7D%20subTreeIdsDirect:(3%2F0%2F115172%2F34288813%2F34290081%2F)",
        "image":  "img/IT_GEDA_online_course_650x365_36422001.jpg",
        "format":  "Online",
        "location":  "-",
        "duration":  "Variable",
        "info":  "Online • Variable",
        "size":  "wide"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Administrative Skills and Tools",
        "title":  "Missions",
        "text":  "Training courses designed to help staff manage missions efficiently, including the declaration of mission expenses after travel, an introduction to EP mission rules, and hands-on training.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=0\u0026sidebarExpanded=true\u0026q=%7B!q.op%3DAND%7D%20mission\u0026rows=2\u0026fq=%7B!tag%3DsubTreeIdsDirect%7D%20subTreeIdsDirect:(3%2F0%2F115172%2F34288813%2F34290081%2F)",
        "image":  "img/eMISS_Mission_rules_and_MISS_application_104595295.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "Variable",
        "info":  "online/classroom • Brussels/Luxembourg • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Behaviour and Attitude at the Workplace",
        "title":  "All Clear",
        "text":  "Understand information security risks, safe conduct practices, and the rules for handling EU classified information (EUCI) within the European Parliament.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=115172\u0026fq%2B=subTreeIds:%221%2F0%2F115172%2F%22\u0026fq=%7B!tag%3DsubTreeIds%7D%20subTreeIds:(2%2F0%2F115172%2F34288577%2F)\u0026fq=%7B!tag%3DsubTreeIdsDirect%7D%20subTreeIdsDirect:(3%2F0%2F115172%2F34288813%2F34290065%2F)\u0026fq=%7B!tag%3DlocationIds%7D%20locationIds:(0%2F115631%2F)\u0026sidebarExpanded=true\u0026q=%7B!q.op%3DAND%7D%20all%20clear\u0026rows=2",
        "image":  "img/banner_euci_98752600.png",
        "format":  "Online",
        "location":  "-",
        "duration":  "1h",
        "info":  "Online • 1h",
        "size":  "wide"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Behaviour and Attitude at the Workplace",
        "title":  "EMAS",
        "text":  "Discover how the EP manages its environmental impact and how you can play a role in achieving its sustainability goals.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=0\u0026sidebarExpanded=true\u0026q=%7B!q.op%3DAND%7D%20%7B!q.op%3DAND%7D%20EMAS\u0026rows=8\u0026fq=%7B!tag%3DsubTreeIdsDirect%7D%20subTreeIdsDirect:(3%2F0%2F115172%2F34288813%2F34290065%2F)",
        "image":  "img/EU_learn_EMAS_training_650x365_107343653.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "Variable",
        "info":  "online/classroom • Brussels/Luxembourg • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Behaviour and Attitude at the Workplace",
        "title":  "Uncouncious Bias",
        "text":  "Be aware of your unconscious biases and learn how to adjust your automatic thinking patterns to improve relationships with others. Particularly useful when recruiting and evaluating performance.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290065/coursetemplates/111894952/description",
        "image":  "img/course_template_description_image_default.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3,5h",
        "info":  "Classroom  • Brussels/Luxembourg • 3,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Behaviour and Attitude at the Workplace",
        "title":  "How to plan and lead a productive meeting ",
        "text":  "Have you had enough of time-wasting meetings? Discover how to organise, lead, and participate in in-person meetings that actually achieve results.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290065/coursetemplates/105839915/description",
        "image":  "img/How_to_plan_and_lead_a_productive_meeting_650x365_98688928.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "4h",
        "info":  "online/classroom • Brussels/Luxembourg • 4h",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Behaviour and Attitude at the Workplace",
        "title":  "Working together in multigenerational teams",
        "text":  "Unlock the power of multigenerational teams. Build understanding, challenge assumptions, and enhance teamwork in this interactive half-day course.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290065/coursetemplates/110383065/description",
        "image":  "img/EU_learn_multigen_650x365_96312006.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3,5h",
        "info":  "Classroom  • Brussels/Luxembourg • 3,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Behaviour and Attitude at the Workplace",
        "title":  "Team activities (\"EP Role Play\", \"Treasure Hunt\", \"May 9th 1950, how it all started\", \"The EP collaboration Path\"",
        "text":  "Team activities include EP role play, a 60-minute simulation of EU decision-making, and a treasure hunt designed to bring history to life.",
        "link":  "",
        "image":  "",
        "format":  "",
        "location":  "",
        "duration":  "",
        "info":  "",
        "size":  "wide"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Powers",
        "title":  "EP Powers and EU Policies",
        "text":  "An insight into competencies given to the EU by the Member States (law, finance, policy, cooperation) and the role the European Parliament plays in shaping EU policies.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288590/coursetemplates/90705434/description",
        "image":  "img/EP_Powers_and_EU_Policies_90705421.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "online/classroom • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Powers",
        "title":  "Rules of Procedure",
        "text":  "Track the journey of Parliamentary reports, committee work, negotiations with other EU institutions, and how laws are adopted.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288590/coursetemplates/106405244/description",
        "image":  "img/LEX_Rules_of_Procedure_and_Beyond_640x365_57244569.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Powers",
        "title":  "Powers of Scrutiny of the European Parliament ",
        "text":  "Explore the European Parliament’s powers to scrutinise EU institutions and ensure accountability.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288590/coursetemplates/106404238/description",
        "image":  "img/EU_learn_Powers_of_Scrutiny_650x365_97642434.png",
        "format":  "Classroom ",
        "location":  "Brussels",
        "duration":  "7h",
        "info":  "Classroom  • Brussels • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Policies",
        "title":  "Legislating for the European Union",
        "text":  "Get a detailed understanding of the EU legislative procedures and learn more about of one of the EP’s core competences.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/109416347/description",
        "image":  "img/LEX_Legislating_for_EU_essential_guide_640x365_36307277.jpg",
        "format":  "Online",
        "location":  "-",
        "duration":  "3,5h",
        "info":  "Online • 3,5h",
        "size":  "wide"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e How the EP works",
        "title":  "Ordinary Legislative Procedure - Walkthrough the OLP / COD procedure - 1st reading",
        "text":  "An outline of the key steps, actors, and documents involved, from the Commission proposal to committee and plenary stages, including negotiations and translation processes.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290099/coursetemplates/106415851/description",
        "image":  "img/EU_learn_Ordinary_Legislative_Procedure_650x365_106328879.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e How the EP works",
        "title":  "Legislative Amendments from A to Z: drafting, tabling, voting",
        "text":  "Join our 1,5-day course on the EU legislative amendment process, including drafting, negotiating, and tabling amendments, with practical insights and expert guidance.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290099/coursetemplates/107616957/description",
        "image":  "img/LEX_Drafting_legislation_640x365_39178194_78410575.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "10,5h",
        "info":  "Classroom  • Brussels/Luxembourg • 10,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e How the EP works",
        "title":  "EU Delegated and Implementing Acts at a glance",
        "text":  "Learn about the role of key EU actors; understand who does what within the EP and discover news related to negotiating the provisions for delegated and implementing acts.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290099/coursetemplates/106415546/description",
        "image":  "img/EU_Delegated_and_Implementing_Acts_at_a_glance_90707046.png",
        "format":  "online/classroom",
        "location":  "Brussels",
        "duration":  "7h",
        "info":  "online/classroom • Brussels • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e How the EP works",
        "title":  "EU Law for non-lawyers",
        "text":  "An in-depth introduction to EU legal sources, the functioning of the EU legal system, and its relationship with Member State laws.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290099/coursetemplates/107617073/description",
        "image":  "img/LEX_EU_Law_for_Non_Lawyers_An_Introduction_to_the_EUs_sources_of_law_640x365_36332398_77551242.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Powers",
        "title":  "Rule of Law as a fundamental value of the European Union",
        "text":  "Learn how the EU safeguards its values: monitoring Rule of Law, responding to democratic backsliding, and using the Article 7 TEU procedure.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288590/coursetemplates/106450760/description",
        "image":  "img/LEX_Rule_of_Law_as_a_Fundamental_Value_of_EU_640x365_55448756.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e How the EP works",
        "title":  "EU Social Law",
        "text":  "How does EU social policy work? Explore its links to the internal market, non-discrimination, and the roles of the EU and Member States.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290099/coursetemplates/106446302/description",
        "image":  "img/sum_best_majors_for_law_school_78169739_81938651.gif",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Policies",
        "title":  "EU Food Law ",
        "text":  "This training course provides a general understanding of Food Law rules, explains the production and distribution processes of goods, and clarifies EU food labelling requirements.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/106470113/description",
        "image":  "img/EU_Food_Law_106470112.jpg",
        "format":  "Online",
        "location":  "-",
        "duration":  "3,5h",
        "info":  "Online • 3,5h",
        "size":  "wide"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Policies",
        "title":  "EU Public Health",
        "text":  "Discover the rules and procedures of EU public health and overall impact on EU citizens.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/106481501/description",
        "image":  "img/LEX_EU_Public_Health_106281916.jpg",
        "format":  "Online",
        "location":  "-",
        "duration":  "7h",
        "info":  "Online • 7h",
        "size":  "wide"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Policies",
        "title":  "Environmental law and the European Green Deal",
        "text":  "Catch up on the latest EU laws tackling climate change and environmental protection, with a clear overview of the European Green Deal.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/106451080/description",
        "image":  "img/LEX__Enviornmental_Law_Green_Deal__68408323.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Policies",
        "title":  "EU Trade Policy and Geoeconomics ",
        "text":  "Understand how the EU shapes global trade - key actors, policy tools, recent developments, and the EU’s strategic outlook.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/106481557/description",
        "image":  "img/LEX_External_Action_and_the_EP_640x365_98314351.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Policies",
        "title":  "Security, Defence and the EU",
        "text":  "The course focuses on key CSDP debates from a European Parliament perspective and the impact of recent developments such as the war in Ukraine and the Strategic Compass.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/106406595/description",
        "image":  "img/LEX_Security_Defence_and_teh_EU_67847401.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Policies",
        "title":  "Asylum, Migration and Border Management",
        "text":  "Get to grips with key legal concepts in EU asylum law, regular and irregular migration, and border management in the Area of Freedom, Security and Justice.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/109628618/description",
        "image":  "img/LEX_EU_Law_and_Policy_in_the_Area_of_Asylum_640x365_57326496.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Policies",
        "title":  "The future of our energy: what is the EU’s policy?",
        "text":  "Access to clean affordable and stable energy sources is crucial today.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/106406264/description",
        "image":  "img/Capture_93494217.PNG",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "online/classroom • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Policies",
        "title":  "Cybersecurity ",
        "text":  "As systems grow more connected, risks grow faster. Learn how to lead, manage, and defend against modern cyber threats with HBR’s expert insights.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/106408215/description",
        "image":  "img/Cybersecurity_105644876.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business",
        "title":  "What you need to know about Economics (and were afraid to ask)",
        "text":  "Understand the forces shaping markets and daily life. Explore supply, demand, competition, public policy, and the global economy.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288577/coursetemplates/106405751/description",
        "image":  "img/LEX_Everyday_economics_650x365_39166703.jpg",
        "format":  "Online",
        "location":  "-",
        "duration":  "7h",
        "info":  "Online • 7h",
        "size":  "wide"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business",
        "title":  "The Multiannual Financial Framework (MFF)",
        "text":  "An overview of the EU’s long-term budget (MFF), what it does, what’s being proposed for 2028–2034, and why it’s often hard for countries and institutions to agree.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/109590132/description",
        "image":  "img/EU_learn_MMF_course_650x365_109467574.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "2h",
        "info":  "Classroom  • Brussels/Luxembourg • 2h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business",
        "title":  "Misinformation, disinformation and beyond",
        "text":  "Disinformation or misinformation? Discover how false narratives are engineered, amplified by AI, and challenged by EU action.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288577/coursetemplates/110043801/description",
        "image":  "img/EU_learn_Disinformation_650x365_109737101.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3.5h",
        "info":  "Classroom  • Brussels/Luxembourg • 3.5h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business",
        "title":  "The European Affordable Housing Plan",
        "text":  "Understand the affordable housing challenge in the European Union, including key trends, housing needs, and the structural drivers affecting housing demand and supply.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/108093602/description",
        "image":  "img/pexels_kindelmedia_7579354_108093519.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3.5h",
        "info":  "Classroom  • Brussels/Luxembourg • 3.5h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business",
        "title":  "EU Cohesion Policy Achievements and Perspectives",
        "text":  "Gain Insight into EU Cohesion Policy.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/112113840/description",
        "image":  "img/hands_waving_flags_europeanunion_108641143.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3.5h",
        "info":  "Classroom  • Brussels/Luxembourg • 3.5h",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-talks-webinars",
        "cataloguePath":  "Events",
        "title":  "EP role play",
        "text":  "Step into their shoes in this short decision-making game. Join fictional political groups, debate, negotiate, and vote. Learn about EP’s core competences in a fun and informative way.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/coursetemplates/89803040/description",
        "image":  "img/EU_learn_EP_role_play_650x365_91503920.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "1,5h",
        "info":  "Classroom  • Brussels/Luxembourg • 1,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-talks-webinars",
        "cataloguePath":  "Events",
        "title":  "EP Talks Channel",
        "text":  "From current affairs to workplace skills, each EP Talk explores a new topic to help you better understand the world around you and strengthen your impact at work.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/41097359/courses/90371898/description",
        "image":  "img/ep_talk_faces_main_template_EUL_90430580.png",
        "format":  "online",
        "location":  "-",
        "duration":  "1,5h",
        "info":  "online • 1,5h",
        "size":  "wide"
    },
    {
        "sectionId":  "ep-talks-webinars",
        "cataloguePath":  "Events",
        "title":  "Evacuation Volunteers - Learning Path Trainings",
        "text":  "Ensure and facilitate safe, orderly evacuations of buildings, supporting all occupants, including persons with reduced mobility.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=0\u0026sidebarExpanded=true\u0026q=%7B!q.op%3DAND%7D%20evacuation%20volunteers\u0026rows=3",
        "image":  "img/volunteers_55298429.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg/Strasbourg",
        "duration":  "Variable",
        "info":  "Classroom  • Brussels/Luxembourg/Strasbourg • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-talks-webinars",
        "cataloguePath":  "Events",
        "title":  "Treasure Hunt at the Museum",
        "text":  "Embark on a treasure hunt through the European House of History, bringing history to life and learn about the history of the European project while connecting with its values.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290065/coursetemplates/110382976/description",
        "image":  "img/20160226_EP_032394A_BBO_113__1__95576947.jpg",
        "format":  "classroom ",
        "location":  "Brussels",
        "duration":  "3h",
        "info":  "classroom  • Brussels • 3h",
        "size":  "standard"
    },
    {
        "sectionId":  "finance-tools",
        "cataloguePath":  "Finance tools \u0026 regulations \u003e Miscellaneous",
        "title":  "Budgetary cycle and budget implementation",
        "text":  "This course provides its participants with the necessary basic knowledge on how to implement Parliament’s budget.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288805/coursetemplates/108085694/description",
        "image":  "img/logo_EP_Fin_Aca_gauche_1_93519722_98830233.png",
        "format":  "classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "finance-tools",
        "cataloguePath":  "Finance tools \u0026 regulations",
        "title":  "Financial Management System (FMS) and WebContracts",
        "text":  "Learn all the FMS and WevbContracts tips and tricks, from beginner to advanced level, with general and role dedicated courses.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288805/programmes/111813936",
        "image":  "img/logo_EP_Fin_Aca_gauche_1_93519722_98830233.png",
        "format":  "Online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "Variable",
        "info":  "Online/classroom • Brussels/Luxembourg • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "finance-tools",
        "cataloguePath":  "Finance tools \u0026 regulations",
        "title":  "PROCUREMENT",
        "text":  "Gain a solid understanding of Procurement\u0027s legal and financial aspects: contract definitions, structure, categories, and the management of low, medium, and high-value contracts.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288805/programmes/111818914",
        "image":  "img/logo_EP_Fin_Aca_gauche_1_93519722_98830233.png",
        "format":  "Online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "variable",
        "info":  "Online/classroom • Brussels/Luxembourg • variable",
        "size":  "standard"
    },
    {
        "sectionId":  "finance-tools",
        "cataloguePath":  "Finance tools \u0026 regulations",
        "title":  "Dealing with VAT exemption in the EP",
        "text":  "Discover more about implementing VAT rules, Parliament privileges, and VAT recovery in Member States.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288805/coursetemplates/106677642/description",
        "image":  "img/logo_EP_Fin_Aca_gauche_1_93519722_98830233.png",
        "format":  "classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3h",
        "info":  "classroom  • Brussels/Luxembourg • 3h",
        "size":  "standard"
    },
    {
        "sectionId":  "finance-tools",
        "cataloguePath":  "Finance tools \u0026 regulations",
        "title":  "Risk Management in the European Parliament",
        "text":  "Are you sure you have identified all the risks surrounding the delivery of your tasks or service?",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290081/programmes/105461556/description",
        "image":  "img/Risk_Management_in_the_European_Parliament_105461259.png",
        "format":  "Online",
        "location":  "-",
        "duration":  "Variable",
        "info":  "Online • Variable",
        "size":  "wide"
    },
    {
        "sectionId":  "language-courses",
        "cataloguePath":  "Interinsitutional catalogue \u003e GoFluent",
        "title":  "goFluent",
        "text":  "goFLUENT is an online language learning platform available 24/7 that will accelerate your learning journeys on any device.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=74789980\u0026sidebarExpanded=true\u0026q=*:*\u0026rows=4",
        "image":  "img/White_Logo_with_Tagline_72404144_75091855.jpg",
        "format":  "online",
        "location":  "-",
        "duration":  "Variable",
        "info":  "online • Variable",
        "size":  "wide"
    },
    {
        "sectionId":  "jean-monnet-academy",
        "cataloguePath":  "Jean Monnet Academy",
        "title":  "Jean Monnet Academy - Our House",
        "text":  "A 3-day seminar on EU history, geography, and Parliament’s role that will make you reflect on the European project’s purpose.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/56512543/coursetemplates/104559512/description",
        "image":  "img/EU_learn_JMA_Our_House_650x365_63881929.jpg",
        "format":  "classroom ",
        "location":  "Bazoches-sur-Guyonne (France)",
        "duration":  "20h",
        "info":  "classroom  • Bazoches-sur-Guyonne (France) • 20h",
        "size":  "standard"
    },
    {
        "sectionId":  "jean-monnet-academy",
        "cataloguePath":  "Jean Monnet Academy",
        "title":  "Jean Monnet Academy - seminar for 20+ officials",
        "text":  "A 3-day seminar on EU origins, recent changes, and career inspiration. that features retired colleagues and external speakers.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/56512543/coursetemplates/104559557/description",
        "image":  "img/EU_learn_JMA_Your_Story_650x365_63927431.jpg",
        "format":  "classroom ",
        "location":  "Bazoches-sur-Guyonne (France)",
        "duration":  "18h",
        "info":  "classroom  • Bazoches-sur-Guyonne (France) • 18h",
        "size":  "standard"
    },
    {
        "sectionId":  "jean-monnet-academy",
        "cataloguePath":  "Jean Monnet Academy",
        "title":  "Jean Monnet Academy - seminar for Administrators",
        "text":  "A 3-day seminar for 5-year Parliament Administrators covering networking, career inspiration, and reconnecting with EU origins.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/56512543/coursetemplates/104559589/description",
        "image":  "img/EU_learn_JMA_Perspectives_650x365_63927169.jpg",
        "format":  "classroom ",
        "location":  "Bazoches-sur-Guyonne (France)",
        "duration":  "18h",
        "info":  "classroom  • Bazoches-sur-Guyonne (France) • 18h",
        "size":  "standard"
    },
    {
        "sectionId":  "jean-monnet-academy",
        "cataloguePath":  "Jean Monnet Academy",
        "title":  "Jean Monnet Academy - seminar for Assistants",
        "text":  "A 3-day seminar for 5-year Parliament Assistants covering networking, career inspiration, and reconnecting with EU origins.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/56512543/coursetemplates/104559622/description",
        "image":  "img/EU_learn_JMA_Perspectives_650x365_63927169.jpg",
        "format":  "classroom ",
        "location":  "Bazoches-sur-Guyonne (France)",
        "duration":  "18h",
        "info":  "classroom  • Bazoches-sur-Guyonne (France) • 18h",
        "size":  "standard"
    },
    {
        "sectionId":  "jean-monnet-academy",
        "cataloguePath":  "Jean Monnet Academy",
        "title":  "Jean Monnet Academy - seminar for Directors",
        "text":  "A 3-day seminar on position change management, Parliament’s challenges, and democratic tools.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/56512543/coursetemplates/104559662/description",
        "image":  "img/EU_learn_JMA_Amplitude_650x365_63522297.jpg",
        "format":  "classroom ",
        "location":  "Bazoches-sur-Guyonne (France)",
        "duration":  "18h",
        "info":  "classroom  • Bazoches-sur-Guyonne (France) • 18h",
        "size":  "standard"
    },
    {
        "sectionId":  "jean-monnet-academy",
        "cataloguePath":  "Jean Monnet Academy",
        "title":  "Jean Monnet Academy - seminar for Heads of Unit",
        "text":  "A 3-day seminar reflecting on the EU project, peer inspiration, and senior manager interviews.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/56512543/coursetemplates/104559715/description",
        "image":  "img/EU_learn_JMA_Perspectives_650x365_63927169.jpg",
        "format":  "classroom ",
        "location":  "Bazoches-sur-Guyonne (France)",
        "duration":  "18h",
        "info":  "classroom  • Bazoches-sur-Guyonne (France) • 18h",
        "size":  "standard"
    },
    {
        "sectionId":  "jean-monnet-academy",
        "cataloguePath":  "Jean Monnet Academy",
        "title":  "Jean Monnet Academy - seminar for newly appointed Administrators ",
        "text":  "A 3-day seminar for new colleagues. A chance to reconnect with EU origins and build peer networks.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/56512543/coursetemplates/104559756/description",
        "image":  "img/EU_learn_JMA_Begin_650x365_63636773.jpg",
        "format":  "classroom ",
        "location":  "Bazoches-sur-Guyonne (France)",
        "duration":  "18h",
        "info":  "classroom  • Bazoches-sur-Guyonne (France) • 18h",
        "size":  "standard"
    },
    {
        "sectionId":  "jean-monnet-academy",
        "cataloguePath":  "Jean Monnet Academy",
        "title":  "Jean Monnet Academy - seminar for newly appointed Assistants",
        "text":  "A 3-day seminar for new colleagues focused on career inspiration and networking with experienced peers.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/56512543/coursetemplates/104559792/description",
        "image":  "img/EU_learn_JMA_Begin_650x365_63636773.jpg",
        "format":  "classroom ",
        "location":  "Bazoches-sur-Guyonne (France)",
        "duration":  "18h",
        "info":  "classroom  • Bazoches-sur-Guyonne (France) • 18h",
        "size":  "standard"
    },
    {
        "sectionId":  "jean-monnet-academy",
        "cataloguePath":  "Jean Monnet Academy",
        "title":  "Jean Monnet Academy - seminar for newly appointed Heads of Unit",
        "text":  "A 3-day seminar on EU project reflection, managerial context, and authority in leadership.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/56512543/coursetemplates/110802987/description",
        "image":  "img/EU_learn_JMA_Exploration_650x365_63881592.jpg",
        "format":  "classroom ",
        "location":  "Bazoches-sur-Guyonne (France)",
        "duration":  "18h",
        "info":  "classroom  • Bazoches-sur-Guyonne (France) • 18h",
        "size":  "standard"
    },
    {
        "sectionId":  "mep-apa-training",
        "cataloguePath":  "MEP \u0026 APA training",
        "title":  "APA Induction: Mandatory online course",
        "text":  "Mandatory training for APAs on financial rules, ethics, harassment prevention, and compliance.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/115172/courses/85294573/description",
        "image":  "img/2_mandatory_training_84058887.png",
        "format":  "Online",
        "location":  "-",
        "duration":  "2h",
        "info":  "Online • 2h",
        "size":  "wide"
    },
    {
        "sectionId":  "mep-apa-training",
        "cataloguePath":  "MEP \u0026 APA training",
        "title":  "Catalogue of courses for MEPs",
        "text":  "Discover the MEPs learning catalogue with courses in work-related skills, languages, communication, research, and IT to support parliamentary work.",
        "link":  "https://epintranet.in.ep.europa.eu/files/live/sites/epintranet/files/learning/learn-mep/index.html",
        "image":  "img/EU_learn_Learn_MEP_650x365_101850138.png",
        "format":  "online/classroom",
        "location":  "Brussels",
        "duration":  "Variable",
        "info":  "online/classroom • Brussels • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "newcomers-mandatory",
        "cataloguePath":  "Newcomers \u0026 mandatory courses",
        "title":  "European Parliament\u0027s Induction Programme",
        "text":  "New to the EP? Don’t miss this interactive, informative, and inspiring course that helps you navigate your new environment, connect the dots, and see where you fit in the bigger picture.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288815/coursetemplates/107790754/description",
        "image":  "img/ep_induction_programme_650x365__002__100092045.png",
        "format":  "classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3 days",
        "info":  "classroom  • Brussels/Luxembourg • 3 days",
        "size":  "standard"
    },
    {
        "sectionId":  "newcomers-mandatory",
        "cataloguePath":  "Newcomers \u0026 mandatory courses",
        "title":  "Newcomers Learning Pack",
        "text":  "The full list of courses in this learning package is set out in the Syllabus tab you will find after you Apply for this learning path.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288815/programmes/78416429/description",
        "image":  "img/LP_Newcommer_ilustration_78416183.PNG",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg/Strasbourg",
        "duration":  "Variable",
        "info":  "online/classroom • Brussels/Luxembourg/Strasbourg • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "newcomers-mandatory",
        "cataloguePath":  "Newcomers \u0026 mandatory courses",
        "title":  "Ten things you need to know about the European Parliament",
        "text":  "Discover the Parliament: its core activities and main players.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290099/coursetemplates/107772627/description",
        "image":  "img/10_things_you_need_to_know_74573671.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg/Strasbourg",
        "duration":  "3,5h",
        "info":  "Classroom  • Brussels/Luxembourg/Strasbourg • 3,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "newcomers-mandatory",
        "cataloguePath":  "Newcomers \u0026 mandatory courses",
        "title":  "Representation - 16 stories of women in the European Parliament",
        "text":  "We know who the fathers of the European integration process were. But who were the mothers?",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288815/coursetemplates/106541544/description",
        "image":  "img/EU_learn_Representation_650x365_87390653.png",
        "format":  "classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "2,5h",
        "info":  "classroom  • Brussels/Luxembourg • 2,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "newcomers-mandatory",
        "cataloguePath":  "Newcomers \u0026 mandatory courses",
        "title":  "Onboarding learning paths",
        "text":  "Start your new role with confidence through tailored onboarding learning paths designed to help you quickly develop the knowledge and skills needed for your position.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=90374928\u0026sidebarExpanded=true\u0026q=%7B!q.op%3DAND%7D%20*:*\u0026rows=10\u0026fq=%7B!tag%3DsubTreeIdsDirect%7D%20subTreeIdsDirect:(2%2F0%2F115172%2F90374928%2F)",
        "image":  "img/Mockup_83972026.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "Variable",
        "info":  "online/classroom • Brussels/Luxembourg • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "newcomers-mandatory",
        "cataloguePath":  "Newcomers \u0026 mandatory courses",
        "title":  "Tours",
        "text":  "Eager to navigate EP buildings and deepen your understanding of the EP? Join the EP guided tours and learn about EP history as well as practical tips about key spots for your daily work.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=115172\u0026fq%2B=subTreeIds:%221%2F0%2F115172%2F%22\u0026fq=%7B!tag%3DsubTreeIds%7D%20subTreeIds:(2%2F0%2F115172%2F34288577%2F)\u0026sidebarExpanded=true\u0026q=%7B!q.op%3DAND%7D%20tour\u0026rows=8",
        "image":  "img/20230316_EP_147095A_DEN_888__2__69792418.jpg",
        "format":  "In person",
        "location":  "Brussels/Luxembourg/Strasbourg",
        "duration":  "Variable",
        "info":  "In person • Brussels/Luxembourg/Strasbourg • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "wellbeing",
        "cataloguePath":  "Wellbeing",
        "title":  "How to stay fit while working at your desk: ergonomic training for healthy work practices",
        "text":  "Small changes, big benefits. Discover practical ways to improve your posture, reduce strain and boost your wellbeing during the working day.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/100536427/coursetemplates/107499903/description",
        "image":  "img/Howtostayfitatyourdesk_ebrITWl0WdncWdCvGaUCzyZFBo_152682_thumb_84963447.jpg",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "3h",
        "info":  "online/classroom • Brussels/Luxembourg • 3h",
        "size":  "standard"
    },
    {
        "sectionId":  "wellbeing",
        "cataloguePath":  "Wellbeing",
        "title":  "Mental health first aid course",
        "text":  "Learn how to support your colleagues facing mental health challenges and become part of our network of Mental Health First Aiders.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/100536427/coursetemplates/108642690/description",
        "image":  "img/Mental_health_First_Aid_95955956.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "14h",
        "info":  "online/classroom • Brussels/Luxembourg • 14h",
        "size":  "standard"
    },
    {
        "sectionId":  "wellbeing",
        "cataloguePath":  "Wellbeing",
        "title":  "Preventing harassment ",
        "text":  "In this Harassment training you will find out more about definitions, detection, mediation, and prevention strategies.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/100536427/coursetemplates/108168801/description",
        "image":  "img/prevent_harrassment_94640291.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "3h",
        "info":  "online/classroom • Brussels/Luxembourg • 3h",
        "size":  "standard"
    },
    {
        "sectionId":  "wellbeing",
        "cataloguePath":  "Wellbeing",
        "title":  "Boost your resilience and thrive under pressure",
        "text":  "Resilience isn’t just about enduring stress - it’s about building habits to perform at your best.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/100536427/coursetemplates/106452796/description",
        "image":  "img/Resilience_at_Work_thumb_650x365_88056299.png",
        "format":  "Blended",
        "location":  "Brussels / Luxembourg / Online",
        "duration":  "2 days",
        "info":  "Blended • Brussels / Luxembourg / Online • 2 days",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Administrative Skills and Tools",
        "title":  "Project management",
        "text":  "Build project management skills through courses covering essentials, methodologies, tools, techniques, as well as exam preparation and certification.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=34288614\u0026sidebarExpanded=true\u0026q=*:*\u0026rows=7",
        "image":  "img/Engage_PM_Certification_Exam_preparation_106909389.png",
        "format":  "Online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "Variable",
        "info":  "Online/classroom • Brussels/Luxembourg • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Behaviour and Attitude at the Workplace",
        "title":  "Diplomatic protocol",
        "text":  "The course provides a practical introduction to diplomatic protocol and etiquette, helping participants feel confident when interacting with counterparts and high-ranking visitors.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/109378527/description",
        "image":  "img/EU_learn_Protocol_650x365_1_108448254.png",
        "format":  "online/classroom",
        "location":  "Brussels",
        "duration":  "7h",
        "info":  "online/classroom • Brussels • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Behaviour and Attitude at the Workplace",
        "title":  "Introduction to Diversity \u0026 Inclusion at work",
        "text":  "Explore diversity matters, learn key concepts and best practices and contribute to an inclusive workplace culture.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/108272983/description",
        "image":  "img/EU_learn_thumb_Diversity_inclusion_650x365_88132879.png",
        "format":  "Classroom course",
        "location":  "Brussels",
        "duration":  "3.5",
        "info":  "Classroom course • Brussels • 3.5",
        "size":  "standard"
    }
];