window.authoritativeCatalogueItems = [
    {
        "sectionId":  "career-development",
        "cataloguePath":  "Career Development",
        "title":  "How to develop professionally",
        "text":  "4 courses:\n1. How to develop professionally - AI to support your professional growth:\nAI is becoming increasingly part of our daily work. When used wisely, AI can help us upskill and reduce repetit...",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=0\u0026sidebarExpanded=true\u0026q=%7B!q.op%3DAND%7D%20%7B!q.op%3DAND%7D%20How%20to%20Develop%20Professionally\u0026rows=4\u0026fq=%7B!tag%3DclassificationIds_41370794%7D%20classificationIds_41370794:(1%2F41370794%2F41374272%2F)",
        "image":  "img/EU_learn_How_to_develop_prof_650x365_107454336.png",
        "format":  "Online",
        "location":  "-",
        "duration":  "3h",
        "info":  "Online • 3h",
        "size":  "standard"
    },
    {
        "sectionId":  "career-development",
        "cataloguePath":  "Career Development",
        "title":  "How to prepare for an internal interview",
        "text":  "This course is designed for those who want to develop and take control of their professional career and achieve (internal) mobility in a short space of time.\nIt\u0027s a high-impact course in a short sp...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/108489565/description",
        "image":  "img/EU_Learn_How_to_prepare_for_internal_interview_108299500.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "8h",
        "info":  "online/classroom • Brussels/Luxembourg • 8h",
        "size":  "standard"
    },
    {
        "sectionId":  "career-development",
        "cataloguePath":  "Career Development",
        "title":  "Developing your personal brand",
        "text":  "•    Module 1 Welcome \u0026 the case for personal branding\n•    Module 2 Know yourself: values, strengths \u0026 audience\n•    Module 3 Craft your story: bio, pitch \u0026 voice\n•    Module 4 Build your presence...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290075/coursetemplates/110236842/description",
        "image":  "img/EU_learn_Develop_personal_brand_650x365_110232425.png",
        "format":  "Classroom ",
        "location":  "Brussels",
        "duration":  "7.5",
        "info":  "Classroom  • Brussels • 7.5",
        "size":  "standard"
    },
    {
        "sectionId":  "career-development",
        "cataloguePath":  "Career Development",
        "title":  "Kick-start your competition preparation",
        "text":  "This course will equip you with proven models and approaches to follow, as well as some quick tips and tricks to help you unlock the secrets to passing your next competition!\n\n",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290075/coursetemplates/106732671/description",
        "image":  "img/Kick_start_competition_prep_Image_81343338_98509988.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7H",
        "info":  "Classroom  • Brussels/Luxembourg • 7H",
        "size":  "standard"
    },
    {
        "sectionId":  "career-development",
        "cataloguePath":  "Career Development",
        "title":  "Collection per EP competence",
        "text":  "•    Module 4 Build your presence: role-play \u0026 group exercise",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=78316164",
        "image":  "img/Competences.png",
        "format":  "Online/classroom",
        "location":  "-",
        "duration":  "Variable",
        "info":  "Online/classroom • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Public speaking ",
        "text":  "The course starts with a short theory part. Participants will learn professional tricks to :\nPrepare efficiently\nIdentify their key messages\nAdapt their content to the audience and the delivery tim...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/106321378/description",
        "image":  "img/public_speaker_98919503.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "3,5h",
        "info":  "online/classroom • Brussels/Luxembourg • 3,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Presenting with impact",
        "text":  "Particular accent will be made on the impact of online presentations and the challenges while presenting or moderating:\nIs your presentation/panel attractive enough to elicit the full engagement of...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/106481527/description",
        "image":  "img/My_presentation_skills_in_virtual_settings_640x365_51342528_78702904_94765412.jpg",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "online/classroom • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Voice techniques for clear communication",
        "text":  "The course starts with short voice exercises and tongue twisters, participants learn brething and delivery techniques to make themselves heard. They learn what makes a presentation, intervention in...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/106322483/description",
        "image":  "img/public_speaking_reading_a_speech_98839391.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "online/classroom • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Tough talks - Mastering the Art of Difficult Conversations",
        "text":  "- build your confidence to engage in difficult conversations\n- know when to have them\n- know how to prepare for them\n- know how to navigate them\n- know how to handle destabilising developments",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/106321632/description",
        "image":  "img/EU_learn_Tough_talks_650x365_98569406.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "4h",
        "info":  "online/classroom • Brussels/Luxembourg • 4h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Brand Guidelines for the European Parliament\u0027s Administration",
        "text":  "You will discover the key principles of branding for the public sector, the relevant branding tools, the strategic foundations, the visual identity building blocks, and their application to various...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/93851499/description",
        "image":  "img/brand_guidelines_93851484.png",
        "format":  "Online",
        "location":  "-",
        "duration":  "Variable",
        "info":  "Online • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "How to facilitate online",
        "text":  "This course introduces how engaging online workshops can be designed, organised and delivered within the EP.\nParticipants will explore how to define the purpose of a workshop, the different roles n...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/95998135/description",
        "image":  "img/Online_workshop_facilitation_tools__flow__and_best_practices_95959586.png",
        "format":  "Online",
        "location":  "-",
        "duration":  "2h",
        "info":  "Online • 2h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Effective networking",
        "text":  "Effective networking is not about collecting contacts. It is about building meaningful, ethical and lasting professional relationships. This interactive course equips participants with practical to...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/107223032/description",
        "image":  "img/course_template_description_image_default.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3,5h",
        "info":  "Classroom  • Brussels/Luxembourg • 3,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Clear language essentials",
        "text":  "We discuss what clear language is and why it matters in Parliament. We then introduce the principles of clear language and Parliament’s Citizens’ language guidelines and focus on applying the guide...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/104685091/description",
        "image":  "img/Clear_Language_Essentials___Graphic_100496148.png",
        "format":  "Online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "2,5H",
        "info":  "Online/classroom • Brussels/Luxembourg • 2,5H",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Getting the most out of feedback",
        "text":  "The topics addressed in this course:\nImproving feedback quality through understanding brain mechanisms\nIdentifying unconscious obstacles which may affect the way I give and receive feedback\nReflect...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/106317255/description",
        "image":  "img/Getting_the_most_out_of_feedback_93656167.png",
        "format":  "Online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Online/classroom • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Back to school and university",
        "text":  "•    Module 5 Sustain \u0026 grow: habits and accountability",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/106634610/description",
        "image":  "img/B2S_Training_logo_99210747.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3,5h",
        "info":  "Classroom  • Brussels/Luxembourg • 3,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Visual thinking: Connect challenges to dynamic sketches",
        "text":  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae justo nec urna facilisis posuere. Praesent commodo, sapien at fermentum aliquet, libero nunc.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/112115541/coursesessions",
        "image":  "img/PowerVisuals_thumb_650x3652_89137204.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7hrs",
        "info":  "Classroom  • Brussels/Luxembourg • 7hrs",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Navigate your emotional intelligence",
        "text":  "Emotional Intelligence (EI) is a set of emotional and social skills and competencies that influence our capability to cope effectively with the demands and pressures of work and life.\n\nThis course...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/100536427/coursetemplates/106774919/description",
        "image":  "img/Emotional_intel_650x365_83105060.png",
        "format":  "classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Brainstorming techniques - how to come up with new ideas",
        "text":  "Are you stuck having only 1 idea when thinking about your complex professional problems and would you like to go beyond it? Would you like to discover how to have many more (innovative) ideas poppi...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/109611791/description",
        "image":  "img/EU_learn_brainstorming_techniques_650x365_107223191.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3,5h",
        "info":  "Classroom  • Brussels/Luxembourg • 3,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Entry-Level Participatory Leadership",
        "text":  "The context in which the European Parliament and the European Union work continues to change and become complex.  Engaging in meaningful conversations has become a crucial strategic action where di...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290075/coursetemplates/106712243/description",
        "image":  "img/EU_learn_Participatory_Leadership_650x3652_82118316.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "24h",
        "info":  "Classroom  • Brussels/Luxembourg • 24h",
        "size":  "standard"
    },
    {
        "sectionId":  "communication-competencies",
        "cataloguePath":  "Communication competencies",
        "title":  "Train the Trainer",
        "text":  "This training is designed to give insight into and increased awareness of how people learn, how to structure a training, the organisation of the content, how to create interactive workshops, online...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/106321897/description",
        "image":  "img/Train_the_Trainer_postits_94737584.jpg",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "4h",
        "info":  "online/classroom • Brussels/Luxembourg • 4h",
        "size":  "standard"
    },
    {
        "sectionId":  "digital-competences",
        "cataloguePath":  "Digital competencies \u003e IT security \u0026 management \u003e Cybersecurity",
        "title":  "Cybersecurity ",
        "text":  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae justo nec urna facilisis posuere. Praesent commodo, sapien at fermentum aliquet, libero nunc.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=34286508",
        "image":  "img/EU learn cybersecurity 650x365.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "Variable",
        "info":  "online/classroom • Brussels/Luxembourg • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "digital-competences",
        "cataloguePath":  "Digital competencies \u003e Other applications",
        "title":  "Data Analytics",
        "text":  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae justo nec urna facilisis posuere. Praesent commodo, sapien at fermentum aliquet, libero nunc.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=34288649",
        "image":  "img/course_template_description_image_default.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "online/classroom • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "digital-competences",
        "cataloguePath":  "Digital competencies \u003e Accessibility",
        "title":  "Acessibility",
        "text":  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae justo nec urna facilisis posuere. Praesent commodo, sapien at fermentum aliquet, libero nunc.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/71037089/programmes/111113376/description",
        "image":  "img/EU_learn_Digigtal_Accessibility_learning_path_650x365_111111558.png",
        "format":  "eLearning",
        "location":  "-",
        "duration":  "Variable",
        "info":  "eLearning • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "digital-competences",
        "cataloguePath":  "Digital competencies \u003e Cloud",
        "title":  "Cloud",
        "text":  "Build cloud computing skills through training in Azure, AWS services, data management, and cloud architecture.\n",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=115172\u0026fq%2B=subTreeIds:%221%2F0%2F115172%2F%22\u0026fq=%7B!tag%3DsubTreeIds%7D%20subTreeIds:(2%2F0%2F115172%2F34288577%2F)\u0026fq=%7B!tag%3DsubTreeIdsDirect%7D%20subTreeIdsDirect:(3%2F0%2F115172%2F34286060%2F36000577%2F)\u0026sidebarExpanded=true\u0026q=%7B!q.op%3DAND%7D%20*:*\u0026rows=3",
        "image":  "img/EU learn Could apps 650x365.png",
        "format":  "online",
        "location":  "-",
        "duration":  "Variable",
        "info":  "online • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "digital-competences",
        "cataloguePath":  "Digital competencies \u003e Adobe",
        "title":  "Adobe Acrobat Pro",
        "text":  "About pdf\nAbout Acrobat\nThe Acrobat interface\nCreating Adobe PDF files\nEnhancing PDF documents\nCombining files in a PDF document\nEditing content in pdf files\nAdding text\nReplacing images\nExporting...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/35771560/coursetemplates/106312511/description",
        "image":  "img/IT_Adobe_Acrobat_thumbnail_650x365_61423696.jpg",
        "format":  "online",
        "location":  "-",
        "duration":  "7h",
        "info":  "online • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "digital-competences",
        "cataloguePath":  "Digital competencies \u003e Adobe",
        "title":  "Adobe Premiere Pro CC (step 1)",
        "text":  "This training course takes place over three consecutive days, during which the following topics will be covered:\nTouring Adobe Premiere Pro CC \nSetting Up a Project\nImporting Media (Media Browser P...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/35771560/coursetemplates/98757260/description",
        "image":  "img/EU_learn_AdobePremiere_650x365_98757256.png",
        "format":  "online",
        "location":  "-",
        "duration":  "21h",
        "info":  "online • 21h",
        "size":  "standard"
    },
    {
        "sectionId":  "digital-competences",
        "cataloguePath":  "Digital competencies ",
        "title":  "Office 365",
        "text":  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae justo nec urna facilisis posuere. Praesent commodo, sapien at fermentum aliquet, libero nunc.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=34288636",
        "image":  "img/EU learn Office 365 650x365.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "Variable",
        "info":  "online/classroom • Brussels/Luxembourg • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "digital-competences",
        "cataloguePath":  "Digital competencies \u003e EP/EU applications",
        "title":  "Digital Basics for Newcomers at the EP",
        "text":  "Step into your new role at the EP with confidence. This 1.5-hour, hands-on session is your fast track to feeling fluent in the digital tools you’ll use every day. Together, we’ll explore tips and t...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288659/coursetemplates/106312215/description",
        "image":  "img/digital_basics_96084258.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3h",
        "info":  "Classroom  • Brussels/Luxembourg • 3h",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Administrative Skills and Tools",
        "title":  "Staff Regulation training",
        "text":  "This course aims to familiarise the personel of the Parliament with staff regulation: recruitment, career, assessment, working time, leave, pensions, and more…\n",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/100658061/coursetemplates/109778704/description",
        "image":  "img/EU_learn_Staff_Regulations_650x365_02.04.2025_107750574.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "6,5h",
        "info":  "Classroom  • Brussels/Luxembourg • 6,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Administrative Skills and Tools",
        "title":  "Document management",
        "text":  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae justo nec urna facilisis posuere. Praesent commodo, sapien at fermentum aliquet, libero nunc.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=0\u0026sidebarExpanded=true\u0026q=%7B!q.op%3DAND%7D%20document%20management\u0026rows=10\u0026fq=%7B!tag%3DsubTreeIdsDirect%7D%20subTreeIdsDirect:(3%2F0%2F115172%2F34288813%2F34290081%2F)",
        "image":  "img/IT_GEDA_online_course_650x365_36422001.jpg",
        "format":  "Online",
        "location":  "-",
        "duration":  "Variable",
        "info":  "Online • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Administrative Skills and Tools",
        "title":  "Missions",
        "text":  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae justo nec urna facilisis posuere. Praesent commodo, sapien at fermentum aliquet, libero nunc.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=0\u0026sidebarExpanded=true\u0026q=%7B!q.op%3DAND%7D%20mission\u0026rows=2\u0026fq=%7B!tag%3DsubTreeIdsDirect%7D%20subTreeIdsDirect:(3%2F0%2F115172%2F34288813%2F34290081%2F)",
        "image":  "img/eMISS_Mission_rules_and_MISS_application_104595295.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "Variable",
        "info":  "online/classroom • Brussels/Luxembourg • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Behaviour and Attitude at the Workplace",
        "title":  "All Clear",
        "text":  "Understand information security risks, safe conduct practices, and the rules for handling EU classified information (EUCI) within the European Parliament.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=115172\u0026fq%2B=subTreeIds:%221%2F0%2F115172%2F%22\u0026fq=%7B!tag%3DsubTreeIds%7D%20subTreeIds:(2%2F0%2F115172%2F34288577%2F)\u0026fq=%7B!tag%3DsubTreeIdsDirect%7D%20subTreeIdsDirect:(3%2F0%2F115172%2F34288813%2F34290065%2F)\u0026fq=%7B!tag%3DlocationIds%7D%20locationIds:(0%2F115631%2F)\u0026sidebarExpanded=true\u0026q=%7B!q.op%3DAND%7D%20all%20clear\u0026rows=2",
        "image":  "img/banner_euci_98752600.png",
        "format":  "Online",
        "location":  "-",
        "duration":  "1h",
        "info":  "Online • 1h",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Behaviour and Attitude at the Workplace",
        "title":  "EMAS",
        "text":  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae justo nec urna facilisis posuere. Praesent commodo, sapien at fermentum aliquet, libero nunc.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=0\u0026sidebarExpanded=true\u0026q=%7B!q.op%3DAND%7D%20%7B!q.op%3DAND%7D%20EMAS\u0026rows=8\u0026fq=%7B!tag%3DsubTreeIdsDirect%7D%20subTreeIdsDirect:(3%2F0%2F115172%2F34288813%2F34290065%2F)",
        "image":  "img/EU_learn_EMAS_training_650x365_107343653.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "Variable",
        "info":  "online/classroom • Brussels/Luxembourg • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Behaviour and Attitude at the Workplace",
        "title":  "Uncouncious Bias",
        "text":  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae justo nec urna facilisis posuere. Praesent commodo, sapien at fermentum aliquet, libero nunc.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290065/coursetemplates/111894952/description",
        "image":  "img/course_template_description_image_default.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3,5h",
        "info":  "Classroom  • Brussels/Luxembourg • 3,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Behaviour and Attitude at the Workplace",
        "title":  "How to plan and lead a productive meeting ",
        "text":  "The first part of our course explores the kind of expectations and frustrations that are associated with meetings. \n\nThen we will unravel and discuss the organisational aspects of a meeting. Why do...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290065/coursetemplates/105839915/description",
        "image":  "img/How_to_plan_and_lead_a_productive_meeting_650x365_98688928.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "4h",
        "info":  "online/classroom • Brussels/Luxembourg • 4h",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Behaviour and Attitude at the Workplace",
        "title":  "Working together in multigenerational teams\n",
        "text":  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae justo nec urna facilisis posuere. Praesent commodo, sapien at fermentum aliquet, libero nunc.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290065/coursetemplates/110383065/description",
        "image":  "img/EU_learn_multigen_650x365_96312006.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3,5h",
        "info":  "Classroom  • Brussels/Luxembourg • 3,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Behaviour and Attitude at the Workplace",
        "title":  "Team activities (\"EP Role Play\", \"Treasure Hunt\", \"May 9th 1950, how it all started\", \"The EP collaboration Path\"",
        "text":  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae justo nec urna facilisis posuere. Praesent commodo, sapien at fermentum aliquet, libero nunc.",
        "link":  "",
        "image":  "",
        "format":  "",
        "location":  "",
        "duration":  "",
        "info":  "",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Powers",
        "title":  "EP Powers and EU Policies",
        "text":  "This course explains the different roles played by the European Parliament in EU policy-making. You start by looking at the range of EU policies in terms of both the different competences that have...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288590/coursetemplates/90705434/description",
        "image":  "img/EP_Powers_and_EU_Policies_90705421.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "online/classroom • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Powers",
        "title":  "Rules of Procedure",
        "text":  "The course follows a journey of a legislative and a non-legislative report through Parliamentary procedures. In particular, it looks into committee procedures and modalities of cooperation between...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288590/coursetemplates/106405244/description",
        "image":  "img/LEX_Rules_of_Procedure_and_Beyond_640x365_57244569.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Powers",
        "title":  "Powers of Scrutiny of the European Parliament ",
        "text":  "This course provides an overview of the powers of the EP to scrutinize other EU institutions. To do so, it discusses key concepts, such as accountability, to systematically identifying instruments,...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288590/coursetemplates/106404238/description",
        "image":  "img/EU_learn_Powers_of_Scrutiny_650x365_97642434.png",
        "format":  "Classroom ",
        "location":  "Brussels",
        "duration":  "7h",
        "info":  "Classroom  • Brussels • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Policies",
        "title":  "Legislating for the European Union",
        "text":  "This  session explains where legislative procedures fit in the EU legal and institutional system and highlights the main features of the decision-making processes involved. You contrast ‘law’ with...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/109416347/description",
        "image":  "img/LEX_Legislating_for_EU_essential_guide_640x365_36307277.jpg",
        "format":  "Online",
        "location":  "-",
        "duration":  "3,5h",
        "info":  "Online • 3,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e How the EP works",
        "title":  "Ordinary Legislative Procedure - Walkthrough the OLP / COD procedure - 1st reading",
        "text":  "This course takes you through the Ordinary Legislative Procedure (COD), focusing on its first reading, presenting the main business steps in perspective,  actors involved actors, and  the  document...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290099/coursetemplates/106415851/description",
        "image":  "img/EU_learn_Ordinary_Legislative_Procedure_650x365_106328879.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e How the EP works",
        "title":  "Legislative Amendments from A to Z: drafting, tabling, voting",
        "text":  "Introduction of rules on EU law making, including drafting of EU legislation\n Presentation of how to prepare and proceed successfully legislative amendments in the European Parliament\nIntroduction...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290099/coursetemplates/107616957/description",
        "image":  "img/LEX_Drafting_legislation_640x365_39178194_78410575.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "10,5h",
        "info":  "Classroom  • Brussels/Luxembourg • 10,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e How the EP works",
        "title":  "EU Delegated and Implementing Acts at a glance",
        "text":  "The course first places delegated and implementing acts in the EU policy cycle and system of EU legal acts. The two types of acts and their systems of control are then discussed in more detail.\nYou...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290099/coursetemplates/106415546/description",
        "image":  "img/EU_Delegated_and_Implementing_Acts_at_a_glance_90707046.png",
        "format":  "online/classroom",
        "location":  "Brussels",
        "duration":  "7h",
        "info":  "online/classroom • Brussels • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e How the EP works",
        "title":  "EU Law for non-lawyers",
        "text":  "This course will provide you with an in-depth introduction to the system of legal sources of the EU. It will present the workings of the EU legal system and the most important principles governing...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290099/coursetemplates/107617073/description",
        "image":  "img/LEX_EU_Law_for_Non_Lawyers_An_Introduction_to_the_EUs_sources_of_law_640x365_36332398_77551242.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Powers",
        "title":  "Rule of Law as a fundamental value of the European Union",
        "text":  "The seminar explains the meaning of respecting of the Rule of Law in an EU context, the mechanisms the EU can avail of to monitor/sanction Member States if they fail in their obligations. and  the...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288590/coursetemplates/106450760/description",
        "image":  "img/LEX_Rule_of_Law_as_a_Fundamental_Value_of_EU_640x365_55448756.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e How the EP works",
        "title":  "EU Social Law",
        "text":  "This course provides an overview of the EU social policy in the context of the recent developments regarding the European Pillar of Social rights. The main focus of the course will be on the follow...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290099/coursetemplates/106446302/description",
        "image":  "img/sum_best_majors_for_law_school_78169739_81938651.gif",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Policies",
        "title":  "EU Food Law ",
        "text":  "This course focusses on the explanation of the fundamental tenets of EU Food Law, whose rules aim to protect human health and consumer interests, and to foster the smooth operation of the single ma...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/106470113/description",
        "image":  "img/EU_Food_Law_106470112.jpg",
        "format":  "Online",
        "location":  "-",
        "duration":  "3,5h",
        "info":  "Online • 3,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Policies",
        "title":  "EU Public Health",
        "text":  "This course will begin with the variety of rules that the EU has adopted to support Member States in the field of health protection. After discussing issues of policy competence and treaty legal ba...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/106481501/description",
        "image":  "img/LEX_EU_Public_Health_106281916.jpg",
        "format":  "Online",
        "location":  "-",
        "duration":  "7h",
        "info":  "Online • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Policies",
        "title":  "Environmental law and the European Green Deal",
        "text":  "This 2-half day training course gives  participants an overview of what the  European Green Deal contains concretely in terms of environmental protection and combatting climate change. In particula...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/106451080/description",
        "image":  "img/LEX__Enviornmental_Law_Green_Deal__68408323.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Policies",
        "title":  "EU Trade Policy and Geoeconomics ",
        "text":  "This course will give a comprehensive overview of the policies, instruments and actors involved in shaping the EU’s external economic relations. We will look at the different dimensions of EU trade...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/106481557/description",
        "image":  "img/LEX_External_Action_and_the_EP_640x365_98314351.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Policies",
        "title":  "Security, Defence and the EU",
        "text":  "\nSince the inception of the Common Foreign and Security Policy in 1993, the EU has come a long way.The Union’s inability to adequately react to the crises in former Yugoslavia in the 1990es has pro...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/106406595/description",
        "image":  "img/LEX_Security_Defence_and_teh_EU_67847401.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Policies",
        "title":  "Asylum, Migration and Border Management",
        "text":  "The primary objective of the training is to explain the policy considerations and legal concepts related to asylum law as well as regular and irregular migration and the related instruments of bord...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/109628618/description",
        "image":  "img/LEX_EU_Law_and_Policy_in_the_Area_of_Asylum_640x365_57326496.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Policies",
        "title":  "The future of our energy: what is the EU’s policy?",
        "text":  "This course provides an overview of the EU energy policy in the context of the Green Deal objectives and the efforts to build an Energy Union. The course will provide  the link between energy polic...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/106406264/description",
        "image":  "img/Capture_93494217.PNG",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "online/classroom • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business \u003e Policies",
        "title":  "Cybersecurity ",
        "text":  "The training is designed to offer an overview of the EU Security Union and the Union’s competences in the field of cybersecurity. It will give an overview of the major cyber security challenges, pr...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/106408215/description",
        "image":  "img/Cybersecurity_105644876.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "Classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business",
        "title":  "What you need to know about Economics (and were afraid to ask)",
        "text":  "This course is scheduled over 2 half days:\n\nDay 1: Microeconomics\n\nThe course covers the following elements: 1. economic systems, goals and economic schools; 2. Key elements of demand theory – elas...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288577/coursetemplates/106405751/description",
        "image":  "img/LEX_Everyday_economics_650x365_39166703.jpg",
        "format":  "Online",
        "location":  "-",
        "duration":  "7h",
        "info":  "Online • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business",
        "title":  "The Multiannual Financial Framework (MFF)",
        "text":  "This course gives a short overview of the EU’s long-term budget (MFF), what it does, what’s being proposed for 2028–2034, and why it’s often hard for countries and institutions to agree.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/109590132/description",
        "image":  "img/EU_learn_MMF_course_650x365_109467574.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "2h",
        "info":  "Classroom  • Brussels/Luxembourg • 2h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business",
        "title":  "Misinformation, disinformation and beyond",
        "text":  "As geostrategic and technological developments accelerate threats in the information space, repercussions for democracy are becoming more visible. This course aims to increase awareness about risks...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288577/coursetemplates/110043801/description",
        "image":  "img/EU_learn_Disinformation_650x365_109737101.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3.5h",
        "info":  "Classroom  • Brussels/Luxembourg • 3.5h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business",
        "title":  "The European Affordable Housing Plan",
        "text":  "This training provides an overview of the affordable housing challenge in the European Union and the Union’s competences in this field. It is grounded in the European Parliament study Mapping the h...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/108093602/description",
        "image":  "img/pexels_kindelmedia_7579354_108093519.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3.5h",
        "info":  "Classroom  • Brussels/Luxembourg • 3.5h",
        "size":  "standard"
    },
    {
        "sectionId":  "eu-policies",
        "cataloguePath":  "EU policies \u0026 EP core business",
        "title":  "EU Cohesion Policy Achievements and Perspectives",
        "text":  "This half-day course is designed for the EP staff to deepen their understanding of the EU Cohesion Policy. Participants will become familiar with the overall architecture of the Cohesion Policy at...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290094/coursetemplates/112113840/description",
        "image":  "img/hands_waving_flags_europeanunion_108641143.jpg",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3.5h",
        "info":  "Classroom  • Brussels/Luxembourg • 3.5h",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-talks-webinars",
        "cataloguePath":  "Events",
        "title":  "EP role play",
        "text":  "You will take part in a 60-minute role-play game, which is a virtual simulation of the European Union’s decision-making process, putting players in the shoes of Members of the European Parliament (...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/coursetemplates/89803040/description",
        "image":  "img/EU_learn_EP_role_play_650x365_91503920.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "1,5h",
        "info":  "Classroom  • Brussels/Luxembourg • 1,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-talks-webinars",
        "cataloguePath":  "Events",
        "title":  "EP Talks Channel",
        "text":  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae justo nec urna facilisis posuere. Praesent commodo, sapien at fermentum aliquet, libero nunc.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/41097359/courses/90371898/description",
        "image":  "img/ep_talk_faces_main_template_EUL_90430580.png",
        "format":  "online",
        "location":  "-",
        "duration":  "1,5h",
        "info":  "online • 1,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-talks-webinars",
        "cataloguePath":  "Events",
        "title":  "Evacuation Volunteers - Learning Path Trainings",
        "text":  "Evacuation volunteers and DG SAFE staff ensure and control the evacuation of the buildings and facilitate the evacuation of occupants, including the evacuation of people with reduced mobility.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=0\u0026sidebarExpanded=true\u0026q=%7B!q.op%3DAND%7D%20evacuation%20volunteers\u0026rows=3",
        "image":  "img/volunteers_55298429.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg/Strasbourg",
        "duration":  "Variable",
        "info":  "Classroom  • Brussels/Luxembourg/Strasbourg • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-talks-webinars",
        "cataloguePath":  "Events",
        "title":  "Treasure Hunt at the Museum",
        "text":  "Embark on an journey through the European House of History with a treasure hunt designed to bring history to life! This engaging activity offers a unique way to learn about the history of the Europ...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290065/coursetemplates/110382976/description",
        "image":  "img/20160226_EP_032394A_BBO_113__1__95576947.jpg",
        "format":  "classroom ",
        "location":  "Brussels",
        "duration":  "3h",
        "info":  "classroom  • Brussels • 3h",
        "size":  "standard"
    },
    {
        "sectionId":  "finance-tools",
        "cataloguePath":  "Finance tools \u0026 regulations \u003e Miscellaneous",
        "title":  "Budgetary cycle and budget implementation",
        "text":  "This course provides its participants with the necessary basic knowledge on how to implement Parliament’s budget. The content of the course covers the structure of the EU and EP budget, the general...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288805/coursetemplates/108085694/description",
        "image":  "img/logo_EP_Fin_Aca_gauche_1_93519722_98830233.png",
        "format":  "classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "7h",
        "info":  "classroom  • Brussels/Luxembourg • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "finance-tools",
        "cataloguePath":  "Finance tools \u0026 regulations",
        "title":  "Financial Management System (FMS) and WebContracts",
        "text":  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae justo nec urna facilisis posuere. Praesent commodo, sapien at fermentum aliquet, libero nunc.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288805/programmes/111813936",
        "image":  "img/logo_EP_Fin_Aca_gauche_1_93519722_98830233.png",
        "format":  "Online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "Variable",
        "info":  "Online/classroom • Brussels/Luxembourg • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "finance-tools",
        "cataloguePath":  "Finance tools \u0026 regulations",
        "title":  "PROCUREMENT",
        "text":  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae justo nec urna facilisis posuere. Praesent commodo, sapien at fermentum aliquet, libero nunc.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288805/programmes/111818914",
        "image":  "img/logo_EP_Fin_Aca_gauche_1_93519722_98830233.png",
        "format":  "Online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "variable",
        "info":  "Online/classroom • Brussels/Luxembourg • variable",
        "size":  "standard"
    },
    {
        "sectionId":  "finance-tools",
        "cataloguePath":  "Finance tools \u0026 regulations",
        "title":  "Dealing with VAT exemption in the EP",
        "text":  "The main subjects covered include:\nimplementing the rules of the Protocol on privileges and immunities regarding Parliament’s purchases (art 3 of PPI)\napplication of the VAT Directive,         \ntre...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288805/coursetemplates/106677642/description",
        "image":  "img/logo_EP_Fin_Aca_gauche_1_93519722_98830233.png",
        "format":  "classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3h",
        "info":  "classroom  • Brussels/Luxembourg • 3h",
        "size":  "standard"
    },
    {
        "sectionId":  "finance-tools",
        "cataloguePath":  "Finance tools \u0026 regulations",
        "title":  "Risk Management in the European Parliament",
        "text":  "This learning path is self-paced and composed of seven training modules:\n \n1. What is Risk Management?\n2. The Risk Coordinator\n3. The Risk Description\n4. Risk Identification Techniques\n5. The Risk...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290081/programmes/105461556/description",
        "image":  "img/Risk_Management_in_the_European_Parliament_105461259.png",
        "format":  "Online",
        "location":  "-",
        "duration":  "Variable",
        "info":  "Online • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "language-courses",
        "cataloguePath":  "Interinsitutional catalogue \u003e GoFluent",
        "title":  "goFluent",
        "text":  "goFLUENT is an online platform, available 24/7, and accessible from any device, that will help you to accelerate your language learning. With goFLUENT, you will be driving your learning journey.\n",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=74789980\u0026sidebarExpanded=true\u0026q=*:*\u0026rows=4",
        "image":  "img/White_Logo_with_Tagline_72404144_75091855.jpg",
        "format":  "online",
        "location":  "-",
        "duration":  "Variable",
        "info":  "online • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "jean-monnet-academy",
        "cataloguePath":  "Jean Monnet Academy",
        "title":  "Jean Monnet Academy - Our House",
        "text":  "This 3-day residential seminar combines the historical and geographical approaches to increase the perception of the European project and its raison d’être. It also presents an in-depth History of...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/56512543/coursetemplates/104559512/description",
        "image":  "img/EU_learn_JMA_Our_House_650x365_63881929.jpg",
        "format":  "classroom ",
        "location":  "Bazoches-sur-Guyonne (France)",
        "duration":  "20h",
        "info":  "classroom  • Bazoches-sur-Guyonne (France) • 20h",
        "size":  "standard"
    },
    {
        "sectionId":  "jean-monnet-academy",
        "cataloguePath":  "Jean Monnet Academy",
        "title":  "Jean Monnet Academy - seminar for 20+ officials",
        "text":  "This newly designed 3-day residential seminar is an opportunity to reconnect with the origins of the European project and to reflect about the changes the last two decades have brought along in the...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/56512543/coursetemplates/104559557/description",
        "image":  "img/EU_learn_JMA_Your_Story_650x365_63927431.jpg",
        "format":  "classroom ",
        "location":  "Bazoches-sur-Guyonne (France)",
        "duration":  "18h",
        "info":  "classroom  • Bazoches-sur-Guyonne (France) • 18h",
        "size":  "standard"
    },
    {
        "sectionId":  "jean-monnet-academy",
        "cataloguePath":  "Jean Monnet Academy",
        "title":  "Jean Monnet Academy - seminar for Administrators",
        "text":  "This 3-day residential seminar is an opportunity to reconnect with the origins of the European project, to get inspiration for a potential next career move and to create a network with peers after...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/56512543/coursetemplates/104559589/description",
        "image":  "img/EU_learn_JMA_Perspectives_650x365_63927169.jpg",
        "format":  "classroom ",
        "location":  "Bazoches-sur-Guyonne (France)",
        "duration":  "18h",
        "info":  "classroom  • Bazoches-sur-Guyonne (France) • 18h",
        "size":  "standard"
    },
    {
        "sectionId":  "jean-monnet-academy",
        "cataloguePath":  "Jean Monnet Academy",
        "title":  "Jean Monnet Academy - seminar for Assistants",
        "text":  "This 3-day residential seminar is an opportunity to reconnect with the origins of the European project, to get inspiration for a potential next career move and to create a network with peers after...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/56512543/coursetemplates/104559622/description",
        "image":  "img/EU_learn_JMA_Perspectives_650x365_63927169.jpg",
        "format":  "classroom ",
        "location":  "Bazoches-sur-Guyonne (France)",
        "duration":  "18h",
        "info":  "classroom  • Bazoches-sur-Guyonne (France) • 18h",
        "size":  "standard"
    },
    {
        "sectionId":  "jean-monnet-academy",
        "cataloguePath":  "Jean Monnet Academy",
        "title":  "Jean Monnet Academy - seminar for Directors",
        "text":  "This 3-day residential seminar is the opportunity to exchange among peers on position change management in a changing House, to listen to Ellen Robson on Parliament’s administration challenges and...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/56512543/coursetemplates/104559662/description",
        "image":  "img/EU_learn_JMA_Amplitude_650x365_63522297.jpg",
        "format":  "classroom ",
        "location":  "Bazoches-sur-Guyonne (France)",
        "duration":  "18h",
        "info":  "classroom  • Bazoches-sur-Guyonne (France) • 18h",
        "size":  "standard"
    },
    {
        "sectionId":  "jean-monnet-academy",
        "cataloguePath":  "Jean Monnet Academy",
        "title":  "Jean Monnet Academy - seminar for Heads of Unit",
        "text":  "The 3-day residential seminar is the opportunity to reflect on the European project, to look at best sources of inspiration from peers and to interview senior managers in an intimate setting allowi...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/56512543/coursetemplates/104559715/description",
        "image":  "img/EU_learn_JMA_Perspectives_650x365_63927169.jpg",
        "format":  "classroom ",
        "location":  "Bazoches-sur-Guyonne (France)",
        "duration":  "18h",
        "info":  "classroom  • Bazoches-sur-Guyonne (France) • 18h",
        "size":  "standard"
    },
    {
        "sectionId":  "jean-monnet-academy",
        "cataloguePath":  "Jean Monnet Academy",
        "title":  "Jean Monnet Academy - seminar for newly appointed Administrators ",
        "text":  "This 3-day residential seminar is an opportunity to reconnect with the origins of the European project, to get inspiration from experienced colleagues and to create a network with peers also at the...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/56512543/coursetemplates/104559756/description",
        "image":  "img/EU_learn_JMA_Begin_650x365_63636773.jpg",
        "format":  "classroom ",
        "location":  "Bazoches-sur-Guyonne (France)",
        "duration":  "18h",
        "info":  "classroom  • Bazoches-sur-Guyonne (France) • 18h",
        "size":  "standard"
    },
    {
        "sectionId":  "jean-monnet-academy",
        "cataloguePath":  "Jean Monnet Academy",
        "title":  "Jean Monnet Academy - seminar for newly appointed Assistants",
        "text":  "This 3-day residential seminar is an opportunity to reconnect with the origins of the European project, to get inspiration from experienced colleagues and to create a network with peers also at the...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/56512543/coursetemplates/104559792/description",
        "image":  "img/EU_learn_JMA_Begin_650x365_63636773.jpg",
        "format":  "classroom ",
        "location":  "Bazoches-sur-Guyonne (France)",
        "duration":  "18h",
        "info":  "classroom  • Bazoches-sur-Guyonne (France) • 18h",
        "size":  "standard"
    },
    {
        "sectionId":  "jean-monnet-academy",
        "cataloguePath":  "Jean Monnet Academy",
        "title":  "Jean Monnet Academy - seminar for newly appointed Heads of Unit",
        "text":  "This 3-day residential seminar is the opportunity to reflect on the European project with Luuk van Middelaar, to look at the managerial context and to work on strengthening the voice of managers an...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/56512543/coursetemplates/110802987/description",
        "image":  "img/EU_learn_JMA_Exploration_650x365_63881592.jpg",
        "format":  "classroom ",
        "location":  "Bazoches-sur-Guyonne (France)",
        "duration":  "18h",
        "info":  "classroom  • Bazoches-sur-Guyonne (France) • 18h",
        "size":  "standard"
    },
    {
        "sectionId":  "mep-apa-training",
        "cataloguePath":  "MEP \u0026 APA training",
        "title":  "APA Induction: Mandatory online course",
        "text":  "This mandatory training for all APAs covers a number of key subjects from financial rules and compliance, transparency and ethics, to harassment prevention and support.\n\nFor each session, there is...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/115172/courses/85294573/description",
        "image":  "img/2_mandatory_training_84058887.png",
        "format":  "Online",
        "location":  "-",
        "duration":  "2h",
        "info":  "Online • 2h",
        "size":  "standard"
    },
    {
        "sectionId":  "mep-apa-training",
        "cataloguePath":  "MEP \u0026 APA training",
        "title":  "Catalogue of courses for MEPs",
        "text":  "Discover the MEPs learning catalogue with courses in  work-related skills, languages, communication, research, and IT to support parliamentary work.",
        "link":  "https://epintranet.in.ep.europa.eu/files/live/sites/epintranet/files/learning/learn-mep/index.html",
        "image":  "img/EU_learn_Learn_MEP_650x365_101850138.png",
        "format":  "online/classroom",
        "location":  "Brussels",
        "duration":  "Variable",
        "info":  "online/classroom • Brussels • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "newcomers-mandatory",
        "cataloguePath":  "Newcomers \u0026 mandatory courses",
        "title":  "European Parliament\u0027s Induction Programme",
        "text":  "This training course will last 3 days. The first day takes place in parallel in Brussels and Luxembourg. The second and third days take place in Brussels.\n\nPlease note that presence is required for...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288815/coursetemplates/107790754/description",
        "image":  "img/ep_induction_programme_650x365__002__100092045.png",
        "format":  "classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "3 days",
        "info":  "classroom  • Brussels/Luxembourg • 3 days",
        "size":  "standard"
    },
    {
        "sectionId":  "newcomers-mandatory",
        "cataloguePath":  "Newcomers \u0026 mandatory courses",
        "title":  "Newcomers Learning Pack",
        "text":  "\nThe full list of courses in this learning package is set out in the Syllabus tab you will find after you Apply for this learning path. Any courses from the learning pack you may have followed alre...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288815/programmes/78416429/description",
        "image":  "img/LP_Newcommer_ilustration_78416183.PNG",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg/Strasbourg",
        "duration":  "Variable",
        "info":  "online/classroom • Brussels/Luxembourg/Strasbourg • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "newcomers-mandatory",
        "cataloguePath":  "Newcomers \u0026 mandatory courses",
        "title":  "Ten things you need to know about the European Parliament",
        "text":  "You will get an insight into what Parliament is about, its core activities and who its main players are. The course will help you understand better the political and administrative motives, and the...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34290099/coursetemplates/107772627/description",
        "image":  "img/10_things_you_need_to_know_74573671.png",
        "format":  "Classroom ",
        "location":  "Brussels/Luxembourg/Strasbourg",
        "duration":  "3,5h",
        "info":  "Classroom  • Brussels/Luxembourg/Strasbourg • 3,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "newcomers-mandatory",
        "cataloguePath":  "Newcomers \u0026 mandatory courses",
        "title":  "Representation - 16 stories of women in the European Parliament",
        "text":  "“We know who the fathers of the European integration process were. But who were the mothers? How did women contribute to building the European House? And which parts of the European Parliament did...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288815/coursetemplates/106541544/description",
        "image":  "img/EU_learn_Representation_650x365_87390653.png",
        "format":  "classroom ",
        "location":  "Brussels/Luxembourg",
        "duration":  "2,5h",
        "info":  "classroom  • Brussels/Luxembourg • 2,5h",
        "size":  "standard"
    },
    {
        "sectionId":  "newcomers-mandatory",
        "cataloguePath":  "Newcomers \u0026 mandatory courses",
        "title":  "Onboarding learning paths",
        "text":  "Start your new role with confidence through tailored onboarding learning paths designed to help you quickly develop the knowledge and skills needed for your position.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=90374928\u0026sidebarExpanded=true\u0026q=%7B!q.op%3DAND%7D%20*:*\u0026rows=10\u0026fq=%7B!tag%3DsubTreeIdsDirect%7D%20subTreeIdsDirect:(2%2F0%2F115172%2F90374928%2F)",
        "image":  "img/Mockup_83972026.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "Variable",
        "info":  "online/classroom • Brussels/Luxembourg • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "newcomers-mandatory",
        "cataloguePath":  "Newcomers \u0026 mandatory courses",
        "title":  "Tours",
        "text":  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae justo nec urna facilisis posuere. Praesent commodo, sapien at fermentum aliquet, libero nunc.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=115172\u0026fq%2B=subTreeIds:%221%2F0%2F115172%2F%22\u0026fq=%7B!tag%3DsubTreeIds%7D%20subTreeIds:(2%2F0%2F115172%2F34288577%2F)\u0026sidebarExpanded=true\u0026q=%7B!q.op%3DAND%7D%20tour\u0026rows=8",
        "image":  "img/20230316_EP_147095A_DEN_888__2__69792418.jpg",
        "format":  "In person",
        "location":  "Brussels/Luxembourg/Strasbourg",
        "duration":  "Variable",
        "info":  "In person • Brussels/Luxembourg/Strasbourg • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "wellbeing",
        "cataloguePath":  "Wellbeing",
        "title":  "How to stay fit while working at your desk: ergonomic training for healthy work practices",
        "text":  "The topics to be covered during this training course will be:\n1. Ergonomics at the office and workstation\n2. Practical exercises: organising and setting up a workstation with a display screen...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/100536427/coursetemplates/107499903/description",
        "image":  "img/Howtostayfitatyourdesk_ebrITWl0WdncWdCvGaUCzyZFBo_152682_thumb_84963447.jpg",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "3h",
        "info":  "online/classroom • Brussels/Luxembourg • 3h",
        "size":  "standard"
    },
    {
        "sectionId":  "wellbeing",
        "cataloguePath":  "Wellbeing",
        "title":  "Mental health first aid course",
        "text":  "Cultivate a culture of compassion and support in your workplace with our 2-day comprehensive Mental Health First Aid course. In this engaging and interactive training, participants will gain practi...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/100536427/coursetemplates/108642690/description",
        "image":  "img/Mental_health_First_Aid_95955956.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "14h",
        "info":  "online/classroom • Brussels/Luxembourg • 14h",
        "size":  "standard"
    },
    {
        "sectionId":  "wellbeing",
        "cataloguePath":  "Wellbeing",
        "title":  "Preventing harassment ",
        "text":  "The definition of harassment in the workplace; a multi-facetted concept\nLearning to recognise its different forms: sexual, moral and psychological harassment\nDetecting and dealing with cases of har...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/100536427/coursetemplates/108168801/description",
        "image":  "img/prevent_harrassment_94640291.png",
        "format":  "online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "3h",
        "info":  "online/classroom • Brussels/Luxembourg • 3h",
        "size":  "standard"
    },
    {
        "sectionId":  "wellbeing",
        "cataloguePath":  "Wellbeing",
        "title":  "Boost your resilience and thrive under pressure",
        "text":  "Resilience is not about enduring or avoiding stress, it is about recovering from stress again and again. During this course you will learn some mental, physical and emotional regulation skills whic...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/100536427/coursetemplates/106452796/description",
        "image":  "img/Resilience_at_Work_thumb_650x365_88056299.png",
        "format":  "Blended",
        "location":  "Brussels / Luxembourg / Online",
        "duration":  "2 days",
        "info":  "Blended • Brussels / Luxembourg / Online • 2 days",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Administrative Skills and Tools",
        "title":  "Project management",
        "text":  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae justo nec urna facilisis posuere. Praesent commodo, sapien at fermentum aliquet, libero nunc.",
        "link":  "https://eulearn.europa.eu/ilp/pages/catalogsearch.jsf?catalogId=34288614\u0026sidebarExpanded=true\u0026q=*:*\u0026rows=7",
        "image":  "img/Engage_PM_Certification_Exam_preparation_106909389.png",
        "format":  "Online/classroom",
        "location":  "Brussels/Luxembourg",
        "duration":  "Variable",
        "info":  "Online/classroom • Brussels/Luxembourg • Variable",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Behaviour and Attitude at the Workplace",
        "title":  "Diplomatic protocol",
        "text":  "The course provides a practical introduction to diplomatic protocol and etiquette, helping participants feel confident when interacting with counterparts and high-ranking visitors. It aims to enabl...",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/109378527/description",
        "image":  "img/EU_learn_Protocol_650x365_1_108448254.png",
        "format":  "online/classroom",
        "location":  "Brussels",
        "duration":  "7h",
        "info":  "online/classroom • Brussels • 7h",
        "size":  "standard"
    },
    {
        "sectionId":  "ep-work-tools",
        "cataloguePath":  "EP work tools \u0026 rules \u003e Behaviour and Attitude at the Workplace",
        "title":  "Introduction to Diversity \u0026 Inclusion at work\n",
        "text":  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae justo nec urna facilisis posuere. Praesent commodo, sapien at fermentum aliquet, libero nunc.",
        "link":  "https://eulearn.europa.eu/ilp/pages/description.jsf#/users/@self/catalogues/34288630/coursetemplates/108272983/description",
        "image":  "img/EU_learn_thumb_Diversity_inclusion_650x365_88132879.png",
        "format":  "Classroom course",
        "location":  "Brussels",
        "duration":  "3.5",
        "info":  "Classroom course • Brussels • 3.5",
        "size":  "standard"
    }
];

